const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.ScriptsInEvents.EGame_Event1_Act1,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.ScriptsInEvents.EGame_Event22_Act3,
		C3.ScriptsInEvents.EGame_Event24,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Mosaico: 0},
	{janela: 0},
	{suport: 0},
	{exit: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{player: 0},
	{Sólido: 0},
	{sensor_solido: 0},
	{caixa: 0},
	{Teclado: 0},
	{Sprite: 0},
	{Direcao: 0},
	{Piscar: 0},
	{porco_patrulheiro: 0},
	{Sensor_Patrulheiro: 0},
	{Sensor_patrulheirodireita: 0},
	{Sensor_patrulheiroesquerda: 0},
	{life_hud: 0},
	{itens_hud: 0},
	{keyy: 0},
	{sensor_solido2: 0},
	{ArteMenu: 0},
	{fundoMenu: 0},
	{txtTitulo: 0},
	{Sprite2: 0},
	{bottonStart: 0},
	{Restart: 0},
	{Menu: 0},
	{Áudio: 0},
	{Texto: 0},
	{Botão: 0},
	{Texto2: 0},
	{Life: 0}
];

self.InstanceType = {
	Mosaico: class extends self.ITilemapInstance {},
	janela: class extends self.ISpriteInstance {},
	suport: class extends self.ISpriteInstance {},
	exit: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	sensor_solido: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	porco_patrulheiro: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro: class extends self.ISpriteInstance {},
	Sensor_patrulheirodireita: class extends self.ISpriteInstance {},
	Sensor_patrulheiroesquerda: class extends self.ISpriteInstance {},
	life_hud: class extends self.ISpriteInstance {},
	itens_hud: class extends self.ISpriteInstance {},
	keyy: class extends self.ISpriteInstance {},
	sensor_solido2: class extends self.ISpriteInstance {},
	ArteMenu: class extends self.ISpriteInstance {},
	fundoMenu: class extends self.ISpriteInstance {},
	txtTitulo: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	bottonStart: class extends self.IButtonInstance {},
	Restart: class extends self.IButtonInstance {},
	Menu: class extends self.IButtonInstance {},
	Áudio: class extends self.IInstance {},
	Texto: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	Texto2: class extends self.ITextInstance {}
}